version: "3"
services:
    media-wiki:
        build: 
            context: .
            dockerfile: dockerfile
        restart: unless-stopped
        ports:
            - 8081:80
        depends_on:
            - database
            - triplestore
        volumes:
            - smw:/var/www/data
            - smw-images:/var/www/html/images
            - smw-sitemap:/var/www/html/sitemap 
            - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
        env_file:
            - mw.env
    database:
        image: mariadb
        restart: unless-stopped
        volumes:
            - smw-db:/var/lib/mysql
        env_file:
            - db.env
    triplestore:
        image: tenforce/virtuoso
        restart: unless-stopped
        ports:
            - 8890:8890
            - 1111:1111
        volumes:
            - ./data:/data
        env_file:
            - ts.env
              #    import-ontology:
              #        build:
              #            context: ontology2smw/.
              #        restart: "no"
              #        depends_on:
              #            - media-wiki
              #        volumes:
              #            - ./ontology2smw/data:/usr/src/app/data
              #        env_file:
              #            - import.env
              #        #profiles:
              #        #    - import


volumes:
    smw:
    smw-images:
    smw-sitemap:
    smw-db:
